name: Sync Repository to GitLab

on: push

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout main
        run: git checkout main

      - name: Pull latest changes from origin/main
        run: git pull --rebase origin main

      - name: Sync to GitLab
        uses: keninkujovic/gitlab-sync@2.1.0
        with:
          gitlab_url: ${{ secrets.GITLAB_URL }}
          username: ${{ secrets.USERNAME }}
          gitlab_pat: ${{ secrets.GITLAB_PAT }}
